//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace instagram.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ViewModels_Users_UserRegisterViewModel_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewModels_Users_UserRegisterViewModel_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("instagram.Resource.ViewModels.Users.UserRegisterViewModel.en", typeof(ViewModels_Users_UserRegisterViewModel_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not allowed to use the Cyrillic alphabet and the &apos;@&apos; sign in the login.
        /// </summary>
        internal static string CirillicError {
            get {
                return ResourceManager.GetString("CirillicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Email.
        /// </summary>
        internal static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already registered..
        /// </summary>
        internal static string EmailNonUnic {
            get {
                return ResourceManager.GetString("EmailNonUnic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format error.
        /// </summary>
        internal static string FormatError {
            get {
                return ResourceManager.GetString("FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum number of characters: 1, Maximum - 30.
        /// </summary>
        internal static string LoginEmailLenghtError {
            get {
                return ResourceManager.GetString("LoginEmailLenghtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of characters 16 characters.
        /// </summary>
        internal static string MaxPhoneLenght {
            get {
                return ResourceManager.GetString("MaxPhoneLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum field length must be at least 5 characters..
        /// </summary>
        internal static string MinPassLenghtError {
            get {
                return ResourceManager.GetString("MinPassLenghtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of characters 30 characters.
        /// </summary>
        internal static string NameMaxLenght {
            get {
                return ResourceManager.GetString("NameMaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name already exists.
        /// </summary>
        internal static string NonUnic {
            get {
                return ResourceManager.GetString("NonUnic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is not must required.
        /// </summary>
        internal static string NotNull {
            get {
                return ResourceManager.GetString("NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password mismatch.
        /// </summary>
        internal static string PassNotCompare {
            get {
                return ResourceManager.GetString("PassNotCompare", resourceCulture);
            }
        }
    }
}
